name: "Build"

on:
  push:
    branches:
      main

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Ubuntu Linux 20.04 LTS
            os: ubuntu-20.04
            triplet: x86_64-unknown-linux-gnu
            artifact: compile-po2mo
            asset_name: linux
          
          - name: Windows Server 2022
            os: windows-2022
            triplet: x86_64-pc-windows-msvc
            artifact: compile-po2mo.exe
            asset_name: windows
          
          - name: macOS 10.15
            os: macos-10.15
            triplet: x86_64-apple-darwin
            artifact: compile-po2mo
            asset_name: macos

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src
      - name: Build
        run: cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target ${{ matrix.triplet }} --release
      - name: Checksum (UNIX)
        if: runner.os != 'Windows'
        run: shasum -a 256 ./target/${{ matrix.triplet }}/release/${{ matrix.artifact }}
      - name: Checksum (Windows)
        if: runner.os == 'Windows'
        run: Get-FileHash ./target/${{ matrix.triplet }}/release/${{ matrix.artifact }} -Algorithm SHA256 | Format-List
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ./target/${{ matrix.triplet }}/release/${{ matrix.artifact }}
